trigger:
  - dev

variables:
  buildConfiguration: "Debug"

stages:
  - stage: BuildPackagePush
    jobs:
      - job: Build
        pool:
          vmImage: "Ubuntu-20.04"
        continueOnError: "true"
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: restore
              projects: "$(System.DefaultWorkingDirectory)/**/*.csproj"
              feedsToUse: "select"
              nugetConfigPath: 'nuget.dev.config'

          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              projects: "$(System.DefaultWorkingDirectory)/**/*.csproj"
              arguments: "--configuration $(BuildConfiguration)"
              feedsToUse: "config"
              nugetConfigPath: 'nuget.dev.config'

          - task: DotNetCoreCLI@2
            displayName: Test
            inputs:
              command: test
              projects: "$(System.DefaultWorkingDirectory)/**/*.csproj"
              feedsToUse: "config"
              nugetConfigPath: 'nuget.dev.config'

          - task: DotNetCoreCLI@2
            displayName: "Pack"
            inputs:
              command: "pack"
              arguments: "--configuration $(buildConfiguration)"
              packagesToPack: "$(System.DefaultWorkingDirectory)/**/*.csproj;!$(System.DefaultWorkingDirectory)/Tests/**/*.csproj"
              nobuild: true
              versioningScheme: "off"

          - task: NuGetCommand@2
            displayName: "Push"
            inputs:
              command: "push"
              feedsToUse: "config"
              packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
              nuGetFeedType: "internal"
              publishVstsFeed: "<your private nuget feed>"
              versioningScheme: "off"
              allowPackageConflicts: true